version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src/app
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
